[package]
name = "hydrated_sloth"
version = "0.1.0"
edition = "2021"

[dependencies]
druid = { version = "0.8.3", features = ["chrono", "serde"] }
serde = { version = "1.0.210", features = ["derive"] }

